package:
  name: pytorchvideo
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
 path: ../..

requirements:

  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - fvcore>=0.1.4
    - iopath
    - av
    - parameterized
    - torchvision>=0.9.0
    {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}

build:
  string: py{{py}}_pyt{{ environ['PYTORCH_VERSION_NODOT']}}
  script: python setup.py install --single-version-externally-managed --record=record.txt # [not win]

about:
  home: https://github.com/facebookresearch/pytorchvideo
  license: Apache 2.0
  license_file: LICENSE
  summary: "Provides common components for video research with PyTorch."
