# Conda environment file
# Usage: `conda env update -f environment.yml`

name: pytorchvideo

channels:
    - conda-forge
    - pytorch-nightly

dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=10.2
